"""
config.py
---------
Single source of truth for the external validation module.
All paths, class name mappings, and constants are defined here.
No other module should hardcode these values.
"""

from __future__ import annotations
from pathlib import Path

# ── Directory layout ───────────────────────────────────────────────────────────
EXT_VAL_DIR  = Path(__file__).resolve().parent.parent
EXT_DIR      = EXT_VAL_DIR.parent
ROOT_DIR     = EXT_DIR.parent

RAW_DIR      = EXT_VAL_DIR / 'data' / 'raw'
PREP_DIR     = EXT_VAL_DIR / 'data' / 'preprocessed'
RESULTS_DIR  = EXT_VAL_DIR / 'results'
FIG_DIR      = RESULTS_DIR / 'figures'
MODEL_PATH   = ROOT_DIR / 'models' / 'final' / 'efficientnetb3_wbc_final.keras'

# Path to the Bodzas test set classification report — generated by 04_evaluate.ipynb
# Used for the side-by-side comparison. If absent, MLL23 metrics are reported alone.
BODZAS_REPORT_PATH = ROOT_DIR / 'results' / 'classification_report.csv'

# ── Image specs ────────────────────────────────────────────────────────────────
TARGET_SIZE    = 300     # EfficientNetB3 input size
MLL23_RAW_SIZE = 288     # MLL23 native resolution (288×288)
IMG_EXTENSIONS = {'.tif', '.tiff', '.png', '.jpg', '.jpeg', '.bmp'}

# ── Class mapping: MLL23 folder name → Bodzas class name ──────────────────────
# Keys  = exact subfolder names after unzipping from Zenodo
# Values = CLASSES entries from src/dataset.py
#
# Only the 9 classes that match Bodzas are listed here.
# Other MLL23 classes (plasma_cell, hairy_cell, etc.) are simply not downloaded.
MLL23_TO_BODZAS: dict[str, str] = {
    'basophil'             : 'Basophile',
    'eosinophil'           : 'Eosinophile',
    'lymphoblast'          : 'Lymphoblast',
    'lymphocyte'           : 'Lymphocyte',
    'monocyte'             : 'Monocyte',
    'myeloblast'           : 'Myeloblast',
    'band_neutrophil'      : 'Neutrophile_Band',
    'segmented_neutrophil' : 'Neutrophile_Segment',
    'normoblast'           : 'Normoblast',
}

# Reverse map: Bodzas class name → MLL23 folder name
BODZAS_TO_MLL23: dict[str, str] = {v: k for k, v in MLL23_TO_BODZAS.items()}

# Expected image counts per class in MLL23 (from published paper)
# Useful for verifying download completeness.
MLL23_EXPECTED_COUNTS: dict[str, int] = {
    'basophil'             :   634,
    'eosinophil'           : 2_456,
    'lymphoblast'          :   180,   # NOTE: confirm exact count from labels_MLL23.csv
    'lymphocyte'           : 5_547,
    'monocyte'             : 2_512,
    'myeloblast'           : 8_619,
    'band_neutrophil'      :   716,
    'segmented_neutrophil' : 7_187,
    'normoblast'           : 2_071,
}
